"""Hand-written test doubles.

These are deliberately hand-written rather than generated by a mocking library: a fake
that has to satisfy the real Protocol fails to compile under mypy when the port changes,
which is how a port change is meant to be discovered.
"""
